structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  3d-modeling/3d-models: 3d-modeling/3d-models.md
  3d-modeling/animations: 3d-modeling/animations.md
  3d-modeling/colliders: 3d-modeling/colliders.md
  3d-modeling/materials: 3d-modeling/materials.md
  3d-modeling/meshes: 3d-modeling/meshes.md
  3d-modeling/textures: 3d-modeling/textures.md
  builder/scene-limitations: sdk7/optimizing/scene-limitations.md
  design-experience/design-games: sdk7/design-experience/design-games.md
  design-experience/mvp-guidelines: sdk7/design-experience/mvp-guidelines.md
  design-experience/ux-ui-guide: sdk7/design-experience/ux-ui-guide.md
  development-guide/3d-model-animations: sdk7/3d-essentials/3d-model-animations.md
  development-guide/async-functions: sdk7/programming-patterns/async-functions.md
  development-guide/audio-streaming: sdk7/media/audio-streaming.md
  development-guide/avatar-modifiers: sdk7/interactivity/player-avatar.md
  development-guide/cli: sdk7/getting-started/using-the-cli.md
  development-guide/click-events: sdk7/interactivity/button-events/click-events.md
  development-guide/coding-scenes: sdk7/getting-started/coding-scenes.md
  development-guide/component-groups: sdk7/architecture/querying-components.md
  development-guide/create-a-dapp: sdk7/blockchain/create-a-dapp.md
  development-guide/create-libraries: sdk7/libraries/create-libraries.md
  development-guide/custom-components: sdk7/architecture/custom-components.md
  development-guide/data-oriented-programming: sdk7/architecture/data-oriented-programming.md
  development-guide/debug-in-preview: sdk7/debugging/debug-in-preview.md
  development-guide/debug-in-prod: sdk7/debugging/debug-in-prod.md
  development-guide/deploying-your-own-transactions-server: sdk7/blockchain/deploying-your-own-transactions-server.md
  development-guide/dev-workflow: sdk7/getting-started/dev-workflow.md
  development-guide/display-a-certified-nft: sdk7/media/display-a-certified-nft.md
  development-guide/entities-components: sdk7/architecture/entities-components.md
  development-guide/entity-positioning: sdk7/3d-essentials/entity-positioning.md
  development-guide/event-listeners: sdk7/interactivity/event-listeners.md
  development-guide/external-links: sdk7/interactivity/external-links.md
  development-guide/game-objects: sdk7/programming-patterns/game-objects.md
  development-guide/installation-guide: scene-editor/get-started/editor-installation.md
  development-guide/libraries/manage-dependencies: sdk7/libraries/manage-dependencies.md
  development-guide/manage-dependencies: sdk7/libraries/manage-dependencies.md
  development-guide/materials: sdk7/3d-essentials/materials.md
  development-guide/move-entities: sdk7/3d-essentials/move-entities.md
  development-guide/move-player: sdk7/interactivity/player-avatar.md
  development-guide/network-connections: sdk7/networking/network-connections.md
  development-guide/onscreen-ui: sdk7/2d-ui/onscreen-ui.md
  development-guide/performance-optimization: sdk7/optimizing/performance-optimization.md
  development-guide/preview-scene: sdk7/getting-started/preview-scene.md
  development-guide/publishing: sdk7/publishing/publishing.md
  development-guide/publishing-permissions: sdk7/publishing/publishing-options.md
  development-guide/raycasting: sdk7/interactivity/raycasting.md
  development-guide/remote-scene-considerations: sdk7/networking/serverless-multiplayer.md
  development-guide/scene-analytics: sdk7/other/scene-analytics.md
  development-guide/scene-blockchain-operations: sdk7/blockchain/scene-blockchain-operations.md
  development-guide/scene-files: sdk7/projects/scene-files.md
  development-guide/scene-limitations: sdk7/optimizing/scene-limitations.md
  development-guide/scene-metadata: sdk7/projects/scene-metadata.md
  development-guide/scene/libraries/manage-dependencies: sdk7/libraries/manage-dependencies.md
  development-guide/sdk-101: sdk7/getting-started/SDK-101.md
  development-guide/sdk7/3d-model-animations: sdk7/3d-essentials/3d-model-animations.md
  development-guide/sdk7/advanced-button-events: sdk7/interactivity/button-events/advanced-button-events.md
  development-guide/sdk7/alpha-testing-guidelines: sdk7/releases/alpha-testing-guidelines.md
  development-guide/sdk7/async-functions: sdk7/programming-patterns/async-functions.md
  development-guide/sdk7/audio-streaming: sdk7/media/audio-streaming.md
  development-guide/sdk7/authoritative-server: sdk7/networking/authoritative-servers.md
  development-guide/sdk7/beta-testing-guidelines: sdk7/releases/alpha-testing-guidelines.md
  development-guide/sdk7/camera: sdk7/3d-essentials/camera.md
  development-guide/sdk7/cli: sdk7/getting-started/using-the-cli.md
  development-guide/sdk7/click-events: sdk7/interactivity/button-events/click-events.md
  development-guide/sdk7/coding-scenes: sdk7/getting-started/coding-scenes.md
  development-guide/sdk7/colliders: sdk7/3d-essentials/colliders.md
  development-guide/sdk7/color-types: sdk7/3d-essentials/color-types.md
  development-guide/sdk7/create-a-dapp: sdk7/blockchain/create-a-dapp.md
  development-guide/sdk7/create-libraries: sdk7/libraries/create-libraries.md
  development-guide/sdk7/custom-components: sdk7/architecture/custom-components.md
  development-guide/sdk7/data-oriented-programming: sdk7/architecture/data-oriented-programming.md
  development-guide/sdk7/debug-in-preview: sdk7/debugging/debug-in-preview.md
  development-guide/sdk7/debug-in-prod: sdk7/debugging/debug-in-prod.md
  development-guide/sdk7/deploying-your-own-transactions-server: sdk7/blockchain/deploying-your-own-transactions-server.md
  development-guide/sdk7/deprecated-functions: sdk7/interactivity/deprecated-functions.md
  development-guide/sdk7/dev-workflow: sdk7/getting-started/dev-workflow.md
  development-guide/sdk7/display-a-certified-nft: sdk7/media/display-a-certified-nft.md
  development-guide/sdk7/dynamic-ui: sdk7/2d-ui/dynamic-ui.md
  development-guide/sdk7/entities-components: sdk7/architecture/entities-components.md
  development-guide/sdk7/entity-positioning: sdk7/3d-essentials/entity-positioning.md
  development-guide/sdk7/event-listeners: sdk7/interactivity/event-listeners.md
  development-guide/sdk7/external-links: sdk7/interactivity/external-links.md
  development-guide/sdk7/game-objects: sdk7/programming-patterns/game-objects.md
  development-guide/sdk7/installation-guide: scene-editor/get-started/editor-installation.md
  development-guide/sdk7/kinds-of-projects: sdk7/projects/kinds-of-project.md
  development-guide/sdk7/libraries/manage-dependencies: sdk7/libraries/manage-dependencies.md
  development-guide/sdk7/lights: sdk7/3d-essentials/lights.md
  development-guide/sdk7/make-discoverable: sdk7/publishing/make-discoverable.md
  development-guide/sdk7/materials: sdk7/3d-essentials/materials.md
  development-guide/sdk7/move-entities: sdk7/3d-essentials/move-entities.md
  development-guide/sdk7/mutable-data: sdk7/programming-patterns/mutable-data.md
  development-guide/sdk7/network-connections: sdk7/networking/network-connections.md
  development-guide/sdk7/npc-avatars: sdk7/interactivity/npc-avatars.md
  development-guide/sdk7/onscreen-ui: sdk7/2d-ui/onscreen-ui.md
  development-guide/sdk7/performance-optimization: sdk7/optimizing/performance-optimization.md
  development-guide/sdk7/player-avatar: sdk7/interactivity/player-avatar.md
  development-guide/sdk7/portable-experiences: sdk7/projects/portable-experiences.md
  development-guide/sdk7/preview-scene: sdk7/getting-started/preview-scene.md
  development-guide/sdk7/publishing: sdk7/publishing/publishing.md
  development-guide/sdk7/publishing-permissions: sdk7/publishing/publishing-options.md
  development-guide/sdk7/querying-components: sdk7/architecture/querying-components.md
  development-guide/sdk7/raycasting: sdk7/interactivity/raycasting.md
  development-guide/sdk7/register-callback: sdk7/interactivity/button-events/register-callback.md
  development-guide/sdk7/remote-scene-considerations: sdk7/networking/serverless-multiplayer.md
  development-guide/sdk7/report-a-bug: sdk7/debugging/report-bug.md
  development-guide/sdk7/runtime-data: sdk7/interactivity/runtime-data.md
  development-guide/sdk7/scene-analytics: sdk7/other/scene-analytics.md
  development-guide/sdk7/scene-blockchain-operations: sdk7/blockchain/scene-blockchain-operations.md
  development-guide/sdk7/scene-files: sdk7/projects/scene-files.md
  development-guide/sdk7/scene-limitations: sdk7/optimizing/scene-limitations.md
  development-guide/sdk7/scene-metadata: sdk7/projects/scene-metadata.md
  development-guide/sdk7/sdk-101: sdk7/getting-started/SDK-101.md
  development-guide/sdk7/second-layer: sdk7/blockchain/second-layer.md
  development-guide/sdk7/serverless-multiplayer: sdk7/networking/serverless-multiplayer.md
  development-guide/sdk7/shape-components: sdk7/3d-essentials/shape-components.md
  development-guide/sdk7/skybox-control: sdk7/interactivity/skybox-control.md
  development-guide/sdk7/smart-wearables: sdk7/projects/smart-wearables.md
  development-guide/sdk7/sounds: sdk7/3d-essentials/sounds.md
  development-guide/sdk7/special-types: sdk7/3d-essentials/special-types.md
  development-guide/sdk7/subscribe-to-changes: sdk7/architecture/subscribe-to-changes.md
  development-guide/sdk7/system-based-events: sdk7/interactivity/button-events/system-based-events.md
  development-guide/sdk7/systems: sdk7/architecture/systems.md
  development-guide/sdk7/testing-guidelines: sdk7/releases/alpha-testing-guidelines.md
  development-guide/sdk7/text: sdk7/3d-essentials/text.md
  development-guide/sdk7/trigger-areas: sdk7/3d-essentials/trigger-areas.md
  development-guide/sdk7/troubleshooting: sdk7/debugging/troubleshooting.md
  development-guide/sdk7/ui-background: sdk7/2d-ui/ui_background.md
  development-guide/sdk7/ui-button-events: sdk7/2d-ui/ui_button_events.md
  development-guide/sdk7/ui-positioning: sdk7/2d-ui/ui-positioning.md
  development-guide/sdk7/ui-special-elements: sdk7/2d-ui/ui_special_types.md
  development-guide/sdk7/ui-text: sdk7/2d-ui/ui_text.md
  development-guide/sdk7/user-data: sdk7/interactivity/user-data.md
  development-guide/sdk7/video-playing: sdk7/media/video-playing.md
  development-guide/sdk7/workspaces: sdk7/projects/workspaces.md
  development-guide/second-layer: sdk7/blockchain/second-layer.md
  development-guide/shape-components: sdk7/3d-essentials/shape-components.md
  development-guide/sounds: sdk7/3d-essentials/sounds.md
  development-guide/special-types: sdk7/3d-essentials/special-types.md
  development-guide/systems: sdk7/architecture/systems.md
  development-guide/text: sdk7/3d-essentials/text.md
  development-guide/trigger-emotes: sdk7/interactivity/player-avatar.md
  development-guide/troubleshooting: sdk7/debugging/troubleshooting.md
  development-guide/user-data: sdk7/interactivity/user-data.md
  development-guide/utils: sdk7/libraries/libraries.md
  development-guide/video-playing: sdk7/media/video-playing.md
  development-guide/workspaces: sdk7/projects/workspaces.md
  editor-plus-code: scene-editor/code/overview.md
  editor/about-scene-editor: scene-editor/get-started/about-editor.md
  editor/custom-items: scene-editor/interactivity/custom-items.md
  editor/import-items: scene-editor/build/import-items.md
  editor/installation-guide: scene-editor/get-started/editor-installation.md
  editor/make-any-item-smart: scene-editor/interactivity/make-any-item-smart.md
  editor/manage-dependencies: sdk7/libraries/manage-dependencies.md
  editor/manage-scenes: scene-editor/get-started/manage-scenes.md
  editor/nfts: scene-editor/build/nfts.md
  editor/preview-scene: sdk7/getting-started/preview-scene.md
  editor/publishing: sdk7/publishing/publishing.md
  editor/smart-items: scene-editor/interactivity/smart-items.md
  editor/smart-items-advanced: scene-editor/interactivity/smart-items-advanced.md
  emotes/avatar-rig: wearables-and-emotes/emotes/avatar-rig.md
  emotes/creating-and-exporting-emotes: wearables-and-emotes/emotes/creating-emotes.md
  emotes/particles-in-emotes: wearables-and-emotes/emotes/particles-in-emotes.md
  emotes/props-and-sounds: wearables-and-emotes/emotes/props-and-sounds.md
  emotes/rig-features: wearables-and-emotes/emotes/rig-features.md
  releases/releases: sdk7/releases/releases.md
  releases/version-agreement: sdk7/releases/version-support-agreement.md
  rewards/api: rewards/integrations.md
  rewards/getting-started: rewards/getting-started.md
  rewards/integrations: rewards/integrations.md
  rewards/overview: rewards/overview.md
  rewards/tx: rewards/transactions.md
  rewards/users: rewards/users-and-roles.md
  scene-editor/build/components: scene-editor/build/components.md
  scene-editor/build/import-assets: scene-editor/build/import-items.md
  scene-editor/build/nfts: scene-editor/build/nfts.md
  scene-editor/code/overview: scene-editor/code/overview.md
  scene-editor/code/reference-items: scene-editor/code/reference-items.md
  scene-editor/configure/settings: scene-editor/configure/scene-settings.md
  scene-editor/faq: scene-editor/faq/README.md
  scene-editor/get-started/essentials: scene-editor/get-started/scene-editor-essentials.md
  scene-editor/get-started/install: scene-editor/get-started/editor-installation.md
  scene-editor/get-started/migrate-into-creator-hub: scene-editor/get-started/migrate-from-web.md
  scene-editor/get-started/overview: scene-editor/get-started/about-editor.md
  scene-editor/interactivity/advanced: scene-editor/interactivity/smart-items-advanced.md
  scene-editor/interactivity/custom-items: scene-editor/interactivity/custom-items.md
  scene-editor/interactivity/make-any-item-smart: scene-editor/interactivity/make-any-item-smart.md
  scene-editor/interactivity/smart-items: scene-editor/interactivity/smart-items.md
  scene-editor/interactivity/states-and-conditions: scene-editor/interactivity/states-and-conditions.md
  scene-editor/interactivity/trigger-area: scene-editor/interactivity/trigger-area.md
  scene-editor/interactivity/video: scene-editor/interactivity/video-screen.md
  scene-editor/live-ops/live-streaming: scene-editor/live-ops/live-streaming.md
  scene-editor/live-ops/scene-admin: scene-editor/live-ops/scene-admin.md
  scene-editor/publish/publish-scene: scene-editor/publish/publish-scene.md
  scenes/sample-scenes: tutorials/examples.md
  sdk7/examples/7: tutorials/examples.md
  sdk7/libraries/7: sdk7/libraries/libraries.md
  sdk7/releases/7: sdk7/releases/v7-alpha.md
  smart-items: scene-editor/interactivity/smart-items.md
  smart-items-advanced: scene-editor/interactivity/smart-items-advanced.md
  tutorials/video: tutorials/video.md
  tutorials/video-emotes: tutorials/video-emotes.md
  wearables-and-emotes/emotes/emotes-overview: wearables-and-emotes/emotes/README.md
  wearables-and-emotes/manage-collections/creating-collection: wearables-and-emotes/manage-collections/creating-a-collection.md
  wearables-and-emotes/manage-collections/uploading-emotes: wearables-and-emotes/manage-collections/uploading-emotes.md
  wearables-and-emotes/manage-collections/uploading-smart-wearables: wearables-and-emotes/manage-collections/uploading-smart-wearables.md
  wearables-and-emotes/manage-collections/uploading-wearables: wearables-and-emotes/manage-collections/uploading-wearables.md
  wearables-and-emotes/wearables/wearables-overview: wearables-and-emotes/wearables/README.md
  wearables/creating-wearables: wearables-and-emotes/wearables/creating-wearables.md
  wearables/curation-committee: wearables-and-emotes/publishing/curation-committee.md
  wearables/linked-wearables: wearables-and-emotes/wearables/linked-wearables.md
  wearables/publishing-collections: wearables-and-emotes/publishing/publishing-collections.md
  web-editor: scene-editor/get-started/about-editor.md
  worlds/about: sdk7/publishing/publishing-options.md
  worlds/cast: sdk7/publishing/publishing-options.md
